<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v4.24.4
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace Auth;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class AuthServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    public function register(
        \Auth\RegisterRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Auth\RegisterResponse {
        /** @var Client\Invoke<\Auth\RegisterRequest, \Auth\RegisterResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/auth.AuthService/Register',
            type: \Auth\RegisterResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    public function login(
        \Auth\LoginRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Auth\LoginResponse {
        /** @var Client\Invoke<\Auth\LoginRequest, \Auth\LoginResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/auth.AuthService/Login',
            type: \Auth\LoginResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
