<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v4.24.4
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace Auth;

use Override;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class AuthServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Auth\AuthServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('auth.AuthService', [
            new Server\Rpc(
                new Server\Handle('Register', \Auth\RegisterRequest::class),
                new Server\UnaryHandler($this->server->register(...)),
            ),
            new Server\Rpc(
                new Server\Handle('Login', \Auth\LoginRequest::class),
                new Server\UnaryHandler($this->server->login(...)),
            ),
        ]);
    }
}
