<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v4.24.4
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace Auth;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
interface AuthServiceServer
{
    public function register(
        \Auth\RegisterRequest $request,
        Metadata $md,
        Cancellation $cancellation,
    ): \Auth\RegisterResponse;

    public function login(\Auth\LoginRequest $request, Metadata $md, Cancellation $cancellation): \Auth\LoginResponse;
}
