<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.31.1
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace kuaukutsu\ec\grpc\generate\php\auth;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class AuthServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    public function register(
        \kuaukutsu\ec\grpc\generate\php\auth\RegisterRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \kuaukutsu\ec\grpc\generate\php\auth\RegisterResponse {
        /** @var Client\Invoke<\kuaukutsu\ec\grpc\generate\php\auth\RegisterRequest, \kuaukutsu\ec\grpc\generate\php\auth\RegisterResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/auth.AuthService/Register',
            type: \kuaukutsu\ec\grpc\generate\php\auth\RegisterResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    public function login(
        \kuaukutsu\ec\grpc\generate\php\auth\LoginRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \kuaukutsu\ec\grpc\generate\php\auth\LoginResponse {
        /** @var Client\Invoke<\kuaukutsu\ec\grpc\generate\php\auth\LoginRequest, \kuaukutsu\ec\grpc\generate\php\auth\LoginResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/auth.AuthService/Login',
            type: \kuaukutsu\ec\grpc\generate\php\auth\LoginResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
