<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.31.1
 * Source: proto/sso/sso.proto
 */

declare(strict_types=1);

namespace kuaukutsu\ec\grpc\generate\php\auth;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class AuthServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function register(
        RegisterRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): RegisterResponse {
        /** @var Client\Invoke<RegisterRequest, RegisterResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/auth.AuthService/Register',
            type: RegisterResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }

    /**
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function login(
        LoginRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): LoginResponse {
        /** @var Client\Invoke<LoginRequest, LoginResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/auth.AuthService/Login',
            type: LoginResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
