<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.8
 *   protoc               — v6.31.1
 */

declare(strict_types=1);

use kuaukutsu\ec\grpc\generate\php\auth\ProtoSsoSsoDescriptorRegistry;
use Thesis\Protobuf\Pool\OnceRegistrar;
use Thesis\Protobuf\Pool\Registry;

Registry::get()->register(
    new OnceRegistrar(new ProtoSsoSsoDescriptorRegistry()),
);
