<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.31.1
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace kuaukutsu\ec\grpc\generate\php\auth;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LoginResponse
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $token = '',
    ) {}
}
