<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v4.24.4
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace Auth;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LoginRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $email = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $password = '',
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public int $appId = 0,
    ) {}
}
