<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.31.1
 * Source: proto/sso/sso.proto
 */

declare(strict_types=1);

namespace kuaukutsu\ec\grpc\generate\php\auth;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class ProtoSsoSsoDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChNwcm90by9zc28vc3NvLnByb3RvEgRhdXRoIkMKD1JlZ2lzdGVyUmVxdWVzdBIUCgVlbWFpbBgBIAEoCVIFZW1haWwSGgoIcGFzc3dvcmQYAiABKAlSCHBhc3N3b3JkIiYKEFJlZ2lzdGVyUmVzcG9uc2USEgoEdXVpZBgBIAEoCVIEdXVpZCJXCgxMb2dpblJlcXVlc3QSFAoFZW1haWwYASABKAlSBWVtYWlsEhoKCHBhc3N3b3JkGAIgASgJUghwYXNzd29yZBIVCgZhcHBfaWQYAyABKAVSBWFwcElkIiUKDUxvZ2luUmVzcG9uc2USFAoFdG9rZW4YASABKAlSBXRva2VuMnoKC0F1dGhTZXJ2aWNlEjkKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaFi5hdXRoLlJlZ2lzdGVyUmVzcG9uc2USMAoFTG9naW4SEi5hdXRoLkxvZ2luUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZUIXSAFaEGF1dGgvcHJvdG87c3NvdjH4AQFKmAUKBhIEAAAcAQoICgEMEgMAABIKCAoBAhIDAgANCggKAQgSAwQAJwoJCgIICxIDBAAnCgoKAgYAEgQGAAkBCgoKAwYAARIDBggTCgsKBAYAAgASAwcEPgoMCgUGAAIAARIDBwgQCgwKBQYAAgACEgMHEiEKDAoFBgACAAMSAwcsPAoLCgQGAAIBEgMIBDUKDAoFBgACAQESAwgIDQoMCgUGAAIBAhIDCA8bCgwKBQYAAgEDEgMIJjMKCgoCBAASBAsADgEKCgoDBAABEgMLCBcKCwoEBAACABIDDAQVCgwKBQQAAgAFEgMMBAoKDAoFBAACAAESAwwLEAoMCgUEAAIAAxIDDBMUCgsKBAQAAgESAw0EGAoMCgUEAAIBBRIDDQQKCgwKBQQAAgEBEgMNCxMKDAoFBAACAQMSAw0WFwoKCgIEARIEEAASAQoKCgMEAQESAxAIGAoLCgQEAQIAEgMRBBQKDAoFBAECAAUSAxEECgoMCgUEAQIAARIDEQsPCgwKBQQBAgADEgMREhMKCgoCBAISBBQAGAEKCgoDBAIBEgMUCBQKCwoEBAICABIDFQQVCgwKBQQCAgAFEgMVBAoKDAoFBAICAAESAxULEAoMCgUEAgIAAxIDFRMUCgsKBAQCAgESAxYEGAoMCgUEAgIBBRIDFgQKCgwKBQQCAgEBEgMWCxMKDAoFBAICAQMSAxYWFwoLCgQEAgICEgMXBBUKDAoFBAICAgUSAxcECQoMCgUEAgICARIDFwoQCgwKBQQCAgIDEgMXExQKCgoCBAMSBBoAHAEKCgoDBAMBEgMaCBUKCwoEBAMCABIDGwQVCgwKBQQDAgAFEgMbBAoKDAoFBAMCAAESAxsLEAoMCgUEAwIAAxIDGxMUYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'proto/sso/sso.proto',
            messages: [
                new File\MessageDescriptor('auth.RegisterRequest', RegisterRequest::class),
                new File\MessageDescriptor('auth.RegisterResponse', RegisterResponse::class),
                new File\MessageDescriptor('auth.LoginRequest', LoginRequest::class),
                new File\MessageDescriptor('auth.LoginResponse', LoginResponse::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'auth.AuthService',
                    methods: [
                        new File\MethodDescriptor('Register', false, false),
                        new File\MethodDescriptor('Login', false, false),
                    ],
                ),
            ],
        ));
    }
}
