<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v4.24.4
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace Auth;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RegisterResponse
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $uuid = '',
    ) {}
}
