<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.31.1
 * Source: sso/sso.proto
 */

declare(strict_types=1);

namespace kuaukutsu\ec\grpc\generate\php\auth;

use Override;
use Thesis\Protobuf\Pool;

/**
 * @api
 */
final readonly class SsoSsoDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cg1zc28vc3NvLnByb3RvEgRhdXRoIkMKD1JlZ2lzdGVyUmVxdWVzdBIUCgVlbWFpbBgBIAEoCVIFZW1haWwSGgoIcGFzc3dvcmQYAiABKAlSCHBhc3N3b3JkIiYKEFJlZ2lzdGVyUmVzcG9uc2USEgoEdXVpZBgBIAEoCVIEdXVpZCJXCgxMb2dpblJlcXVlc3QSFAoFZW1haWwYASABKAlSBWVtYWlsEhoKCHBhc3N3b3JkGAIgASgJUghwYXNzd29yZBIVCgZhcHBfaWQYAyABKAVSBWFwcElkIiUKDUxvZ2luUmVzcG9uc2USFAoFdG9rZW4YASABKAlSBXRva2VuMnoKC0F1dGhTZXJ2aWNlEjkKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaFi5hdXRoLlJlZ2lzdGVyUmVzcG9uc2USMAoFTG9naW4SEi5hdXRoLkxvZ2luUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZUIVWhBhdXRoL3Byb3RvO3Nzb3Yx+AEBSpgFCgYSBAAAHAEKCAoBDBIDAAASCggKAQISAwIADQoICgEIEgMEACcKCQoCCAsSAwQAJwoKCgIGABIEBgAJAQoKCgMGAAESAwYIEwoLCgQGAAIAEgMHBD4KDAoFBgACAAESAwcIEAoMCgUGAAIAAhIDBxIhCgwKBQYAAgADEgMHLDwKCwoEBgACARIDCAQ1CgwKBQYAAgEBEgMICA0KDAoFBgACAQISAwgPGwoMCgUGAAIBAxIDCCYzCgoKAgQAEgQLAA4BCgoKAwQAARIDCwgXCgsKBAQAAgASAwwEFQoMCgUEAAIABRIDDAQKCgwKBQQAAgABEgMMCxAKDAoFBAACAAMSAwwTFAoLCgQEAAIBEgMNBBgKDAoFBAACAQUSAw0ECgoMCgUEAAIBARIDDQsTCgwKBQQAAgEDEgMNFhcKCgoCBAESBBAAEgEKCgoDBAEBEgMQCBgKCwoEBAECABIDEQQUCgwKBQQBAgAFEgMRBAoKDAoFBAECAAESAxELDwoMCgUEAQIAAxIDERITCgoKAgQCEgQUABgBCgoKAwQCARIDFAgUCgsKBAQCAgASAxUEFQoMCgUEAgIABRIDFQQKCgwKBQQCAgABEgMVCxAKDAoFBAICAAMSAxUTFAoLCgQEAgIBEgMWBBgKDAoFBAICAQUSAxYECgoMCgUEAgIBARIDFgsTCgwKBQQCAgEDEgMWFhcKCwoEBAICAhIDFwQVCgwKBQQCAgIFEgMXBAkKDAoFBAICAgESAxcKEAoMCgUEAgICAxIDFxMUCgoKAgQDEgQaABwBCgoKAwQDARIDGggVCgsKBAQDAgASAxsEFQoMCgUEAwIABRIDGwQKCgwKBQQDAgABEgMbCxAKDAoFBAMCAAMSAxsTFGIGcHJvdG8z';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), [
            'auth.RegisterRequest' => new Pool\MessageMetadata(\kuaukutsu\ec\grpc\generate\php\auth\RegisterRequest::class),
            'auth.RegisterResponse' => new Pool\MessageMetadata(\kuaukutsu\ec\grpc\generate\php\auth\RegisterResponse::class),
            'auth.LoginRequest' => new Pool\MessageMetadata(\kuaukutsu\ec\grpc\generate\php\auth\LoginRequest::class),
            'auth.LoginResponse' => new Pool\MessageMetadata(\kuaukutsu\ec\grpc\generate\php\auth\LoginResponse::class),
        ]);
    }
}
